name: Salesforce Deploy / Validate Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action"
        required: true
        default: "Deploy to Sandbox"
        type: choice
        options:
          - Deploy to Sandbox
          - Deploy to Production
          - Validate in Sandbox
          - Validate in Production

jobs:
  operate:
    name: "${{ github.event.inputs.action }}"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          echo "Trying npm install..."
          if npm install sfdx-cli --global; then
            echo "Installed via npm. sfdx version: $(sfdx --version)"
          else
            echo "npm install failed, downloading tarball..."
            wget -q https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz -O sfdx.tar.xz
            mkdir sfdx-cli
            tar xJf sfdx.tar.xz -C sfdx-cli --strip-components 1
            echo "PATH=$(pwd)/sfdx-cli/bin:$PATH" >> $GITHUB_ENV
            echo "Installed via download. sfdx version: $(sfdx --version)"
          fi

      - name: Authenticate to Salesforce Org
        run: |
          case "${{ github.event.inputs.action }}" in
            *Production*) ORG_ALIAS=prod; SFDX_URL=https://login.salesforce.com ;;
            *) ORG_ALIAS=sandbox; SFDX_URL=https://test.salesforce.com ;;
          esac
          echo "Authenticating to $ORG_ALIAS..."
          sfdx force:auth:device:login -d -a "$ORG_ALIAS" -r "$SFDX_URL"

      - name: Execute Action
        run: |
          ACTION="${{ github.event.inputs.action }}"
          ORG_ALIAS=$( [[ "$ACTION" =~ Production ]] && echo "prod" || echo "sandbox" )

          if [[ "$ACTION" == Validate* ]]; then
            echo "Validating (dry-run) in $ORG_ALIAS..."
            sfdx force:source:deploy -p force-app -u "$ORG_ALIAS" --checkonly --testlevel NoTestRun
          else
            echo "Deploying to $ORG_ALIAS..."
            sfdx force:source:deploy -p force-app -u "$ORG_ALIAS" --testlevel NoTestRun
          fi
